### ISSUE TITLE
folder upload

### ISSUE THREAD

**Issue by h-enes-simsek** [Itz-fork/Gofile2#3]
Hello,
I encountered the following error while uploading a folder. I was using venv and I redacted full paths in the error log below.

```
Traceback (most recent call last):
  File "...\lib\site-packages\gofile2\gofile2.py", line 144, in upload
    return self._api_resp_handler(upload_file)
  File "...\lib\site-packages\gofile2\gofile2.py", line 37, in _api_resp_handler
    raise ResponseError(error)
gofile2.errors.ResponseError: parentFolder

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\gofile.io\test.py", line 10, in <module>
    g_a.upload_folder(path="test_folder/test_folder_2pic")
  File "...\lib\site-packages\gofile2\gofile2.py", line 101, in upload_folder
    udt = self.upload(file, folderId)
  File "...\lib\site-packages\gofile2\gofile2.py", line 146, in upload
    raise JobFailed(
gofile2.errors.JobFailed: Error Happend: Error Happend: parentFolder

Report this at ----> https://github.com/Itz-fork/Gofile2/issues

Report this at ----> https://github.com/Itz-fork/Gofile2/issues
```

My thoughts:
There is no mechanism to upload a folder to the server. They suggest uploading a file once and with using the id of the automatically created folder, uploading other files sequentially. Did you realize this mechanism or I am missing something?

Thank you for the lib.

**Comment by partiallywritten** [comment]
> They suggest uploading a file once and with using the id of the automatically created folder, uploading other files sequentially.

This works only if you provide your api token otherwise you'll get a error saying `error-owner`. As of now you can use the folder upload function only if you initialize with token arg.

Check commit: [8024375](https://github.com/Itz-fork/Gofile2/commit/8024375d3af3182207c7b0f46b0352feaf3e7494)

**Comment by h-enes-simsek** [comment]
Thank you for your immediate response. Apparently, you solved the problem but made a very simple syntax error. I fixed for you and opened a pull request. Thank you again.
